### PR TITLE
feat(xds): add xds server and fix some bugs

### PR DESCRIPTION
**Pull request by marlonfan**

### CODE REVIEW

**Comment by AlexStocks** [comment]
@marlonfan 这里面有些注释是中文，麻烦改成英文。虽然很多不是你写的。

**Comment by marlonfan** [comment]
> 

Ok. I'll fix it.

**Comment by marlonfan** [comment]
> @marlonfan 这里面有些注释是中文，麻烦改成英文。虽然很多不是你写的。

Ok. I'll fix it.

**Review by AlexStocks — APPROVED** [review]

**Comment by marlonfan** [comment]
etcd version is not compatible with go 1.14.

Is it considered to remove the ci of 1.14? @ztelur

**Review by baerwang — APPROVED** [review]

**Comment by ztelur** [comment]
LGTM, Thanks for removing all Chinese comment which already exists before this pr.

**Review by ztelur — APPROVED** [review]

**Pull request merged**
